CREATE TABLE `test_allbyte_cn`.`Untitled`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '用户名',
  `passhash` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `secret` blob NOT NULL,
  `email` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status` enum('pending','confirmed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `added` datetime NULL DEFAULT NULL,
  `last_login` datetime NULL DEFAULT NULL,
  `last_access` datetime NULL DEFAULT NULL,
  `last_home` datetime NULL DEFAULT NULL,
  `last_offer` datetime NULL DEFAULT NULL,
  `forum_access` datetime NULL DEFAULT NULL,
  `last_staffmsg` datetime NULL DEFAULT NULL,
  `last_pm` datetime NULL DEFAULT NULL,
  `last_comment` datetime NULL DEFAULT NULL,
  `last_post` datetime NULL DEFAULT NULL,
  `last_browse` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `last_music` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `last_catchup` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `editsecret` blob NOT NULL,
  `privacy` enum('strong','normal','low') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  `stylesheet` tinyint(3) UNSIGNED NOT NULL DEFAULT 1,
  `caticon` tinyint(3) UNSIGNED NOT NULL DEFAULT 1,
  `fontsize` enum('small','medium','large') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'medium',
  `info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `acceptpms` enum('yes','friends','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `commentpm` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `ip` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `class` tinyint(3) UNSIGNED NOT NULL DEFAULT 1,
  `max_class_once` tinyint(4) NOT NULL DEFAULT 1,
  `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `uploaded` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `downloaded` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `seedtime` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `leechtime` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `title` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `country` smallint(5) UNSIGNED NOT NULL DEFAULT 107,
  `notifs` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `modcomment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `enabled` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `avatars` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `donor` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `donated` decimal(8, 2) NOT NULL DEFAULT 0.00,
  `donated_cny` decimal(8, 2) NOT NULL DEFAULT 0.00,
  `donoruntil` datetime NULL DEFAULT NULL,
  `warned` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `warneduntil` datetime NULL DEFAULT NULL,
  `noad` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `noaduntil` datetime NULL DEFAULT NULL,
  `torrentsperpage` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `topicsperpage` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `postsperpage` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `clicktopic` enum('firstpage','lastpage') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'firstpage',
  `deletepms` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `savepms` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `showhot` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `showclassic` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `support` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `picker` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `stafffor` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `supportfor` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `pickfor` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `supportlang` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `passkey` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `promotion_link` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `uploadpos` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `forumpost` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `downloadpos` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `clientselect` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `signatures` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `signature` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `lang` smallint(5) UNSIGNED NOT NULL DEFAULT 6,
  `cheat` smallint(6) NOT NULL DEFAULT 0,
  `download` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `upload` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `isp` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `invites` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `invited_by` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `gender` enum('Male','Female','N/A') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'N/A',
  `vip_added` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `vip_until` datetime NULL DEFAULT NULL,
  `seedbonus` decimal(20, 1) NOT NULL DEFAULT 0.0,
  `charity` decimal(10, 1) NOT NULL DEFAULT 0.0,
  `bonuscomment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `parked` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `leechwarn` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `leechwarnuntil` datetime NULL DEFAULT NULL,
  `lastwarned` datetime NULL DEFAULT NULL,
  `timeswarned` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `warnedby` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `sbnum` smallint(5) UNSIGNED NOT NULL DEFAULT 70,
  `sbrefresh` smallint(5) UNSIGNED NOT NULL DEFAULT 120,
  `hidehb` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'no',
  `showimdb` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `showdescription` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `showcomment` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `showclienterror` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `showdlnotice` tinyint(1) NOT NULL DEFAULT 1,
  `tooltip` enum('minorimdb','medianimdb','off') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'off',
  `shownfo` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `timetype` enum('timeadded','timealive') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'timealive',
  `appendsticky` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `appendnew` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `appendpromotion` enum('highlight','word','icon','off') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'icon',
  `appendpicked` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `dlicon` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `bmicon` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `showsmalldescr` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `showcomnum` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'yes',
  `showlastcom` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'no',
  `showlastpost` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'no',
  `pmnum` tinyint(3) UNSIGNED NOT NULL DEFAULT 10,
  `school` smallint(5) UNSIGNED NOT NULL DEFAULT 35,
  `showfb` enum('yes','no') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `page` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `two_step_secret` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `seed_points` decimal(20, 1) NOT NULL DEFAULT 0.0,
  `seed_points_per_hour` decimal(20, 1) NOT NULL DEFAULT 0.0,
  `attendance_card` int(11) NOT NULL DEFAULT 0,
  `offer_allowed_count` int(11) NOT NULL DEFAULT 0,
  `seed_points_updated_at` datetime NULL DEFAULT NULL,
  `seed_time_updated_at` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `username`(`username`) USING BTREE,
  INDEX `status_added`(`status`, `added`) USING BTREE,
  INDEX `last_access`(`last_access`) USING BTREE,
  INDEX `ip`(`ip`) USING BTREE,
  INDEX `class`(`class`) USING BTREE,
  INDEX `uploaded`(`uploaded`) USING BTREE,
  INDEX `downloaded`(`downloaded`) USING BTREE,
  INDEX `country`(`country`) USING BTREE,
  INDEX `enabled`(`enabled`) USING BTREE,
  INDEX `warned`(`warned`) USING BTREE,
  INDEX `passkey`(`passkey`) USING BTREE,
  INDEX `cheat`(`cheat`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10001 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;