package constant

const DEFAULT_BONUS_CANCEL_ONE_HIT_AND_RUN = 10000
const DEFAULT_BONUS_BUY_ATTENDANCE_CARD = 1000
const DEFAULT_BONUS_BUY_TEMPORARY_INVITE = 500
const DEFAULT_BONUS_BUY_RAINBOW_ID = 5000
const DEFAULT_BONUS_BUY_CHANGE_USERNAME_CARD = 100000

const BUSINESS_TYPE_CANCEL_HIT_AND_RUN = 1
const BUSINESS_TYPE_BUY_MEDAL = 2
const BUSINESS_TYPE_BUY_ATTENDANCE_CARD = 3
const BUSINESS_TYPE_STICKY_PROMOTION = 4
const BUSINESS_TYPE_POST_REWARD = 5
const BUSINESS_TYPE_EXCHANGE_UPLOAD = 6
const BUSINESS_TYPE_EXCHANGE_INVITE = 7
const BUSINESS_TYPE_CUSTOM_TITLE = 8
const BUSINESS_TYPE_BUY_VIP = 9
const BUSINESS_TYPE_GIFT_TO_SOMEONE = 10
const BUSINESS_TYPE_NO_AD = 11
const BUSINESS_TYPE_GIFT_TO_LOW_SHARE_RATIO = 12
const BUSINESS_TYPE_LUCKY_DRAW = 13
const BUSINESS_TYPE_EXCHANGE_DOWNLOAD = 14
const BUSINESS_TYPE_BUY_TEMPORARY_INVITE = 15
const BUSINESS_TYPE_BUY_RAINBOW_ID = 16
const BUSINESS_TYPE_BUY_CHANGE_USERNAME_CARD = 17
const BUSINESS_TYPE_GIFT_MEDAL = 18
const BUSINESS_TYPE_BUY_TORRENT = 19

const BUSINESS_TYPE_ROLE_WORK_SALARY = 1000
const BUSINESS_TYPE_TORRENT_BE_DOWNLOADED = 1001
