server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  mysql:
    dsn: root:qqqq@tcp(localhost:3306)/tset_hdkyl_in?loc=Local&parseTime=true&charset=utf8mb4
    debug: true
  redis:
    addr: localhost:6379
    username: 
    password: 

