package biz

import "time"

type User struct {
	Id                  uint64    `json:"id"`
	Username            string    `json:"username"`
	Passhash            string    `json:"passhash"`
	Secret              string    `json:"secret"`
	Email               string    `json:"email"`
	Status              string    `json:"status"`
	Added               time.Time `json:"added"`
	LastLogin           time.Time `json:"last_login"`
	LastAccess          time.Time `json:"last_access"`
	LastHome            time.Time `json:"last_home"`
	LastOffer           time.Time `json:"last_offer"`
	ForumAccess         time.Time `json:"forum_access"`
	LastStaffMsg        time.Time `json:"last_staffmsg"`
	LastPM              time.Time `json:"last_pm"`
	LastComment         time.Time `json:"last_comment"`
	LastPost            time.Time `json:"last_post"`
	LastBrowse          uint32    `json:"last_browse"`
	LastMusic           uint32    `json:"last_music"`
	LastCatchup         uint32    `json:"last_catchup"`
	EditSecret          string    `json:"editsecret"`
	Privacy             string    `json:"privacy"`
	Stylesheet          uint8     `json:"stylesheet"`
	Caticon             uint8     `json:"caticon"`
	FontSize            string    `json:"fontsize"`
	Info                string    `json:"info"`
	AcceptPMS           string    `json:"acceptpms"`
	CommentPM           string    `json:"commentpm"`
	IP                  string    `json:"ip"`
	Class               uint8     `json:"class"`
	MaxClassOnce        int8      `json:"max_class_once"`
	Avatar              string    `json:"avatar"`
	Uploaded            uint64    `json:"uploaded"`
	Downloaded          uint64    `json:"downloaded"`
	Seedtime            uint64    `json:"seedtime"`
	Leechtime           uint64    `json:"leechtime"`
	Title               string    `json:"title"`
	Country             uint16    `json:"country"`
	Notifs              string    `json:"notifs"`
	ModComment          string    `json:"modcomment"`
	Enabled             string    `json:"enabled"`
	Avatars             string    `json:"avatars"`
	Donor               string    `json:"donor"`
	Donated             float64   `json:"donated"`
	DonatedCNY          float64   `json:"donated_cny"`
	DonorUntil          time.Time `json:"donoruntil"`
	Warned              string    `json:"warned"`
	WarnedUntil         time.Time `json:"warneduntil"`
	NoAd                string    `json:"noad"`
	NoAdUntil           time.Time `json:"noaduntil"`
	TorrentsPerPage     uint8     `json:"torrentsperpage"`
	TopicsPerPage       uint8     `json:"topicsperpage"`
	PostsPerPage        uint8     `json:"postsperpage"`
	ClickTopic          string    `json:"clicktopic"`
	DeletePMS           string    `json:"deletepms"`
	SavePMS             string    `json:"savepms"`
	ShowHot             string    `json:"showhot"`
	ShowClassic         string    `json:"showclassic"`
	Support             string    `json:"support"`
	Picker              string    `json:"picker"`
	StaffFor            string    `json:"stafffor"`
	SupportFor          string    `json:"supportfor"`
	PickFor             string    `json:"pickfor"`
	SupportLang         string    `json:"supportlang"`
	Passkey             string    `json:"passkey"`
	PromotionLink       string    `json:"promotion_link"`
	UploadPos           string    `json:"uploadpos"`
	ForumPost           string    `json:"forumpost"`
	DownloadPos         string    `json:"downloadpos"`
	ClientSelect        uint8     `json:"clientselect"`
	Signatures          string    `json:"signatures"`
	Signature           string    `json:"signature"`
	Lang                uint16    `json:"lang"`
	Cheat               int16     `json:"cheat"`
	Download            uint32    `json:"download"`
	Upload              uint32    `json:"upload"`
	ISP                 uint8     `json:"isp"`
	Invites             uint16    `json:"invites"`
	InvitedBy           uint32    `json:"invited_by"`
	Gender              string    `json:"gender"`
	VIPAdded            string    `json:"vip_added"`
	VIPUntil            time.Time `json:"vip_until"`
	SeedBonus           float64   `json:"seedbonus"`
	Charity             float64   `json:"charity"`
	BonusComment        string    `json:"bonuscomment"`
	Parked              string    `json:"parked"`
	LeechWarn           string    `json:"leechwarn"`
	LeechWarnUntil      time.Time `json:"leechwarnuntil"`
	LastWarned          time.Time `json:"lastwarned"`
	TimesWarned         uint8     `json:"timeswarned"`
	WarnedBy            uint32    `json:"warnedby"`
	SBNum               uint16    `json:"sbnum"`
	SBRefresh           uint16    `json:"sbrefresh"`
	HideHB              string    `json:"hidehb"`
	ShowIMDB            string    `json:"showimdb"`
	ShowDescription     string    `json:"showdescription"`
	ShowComment         string    `json:"showcomment"`
	ShowClientError     string    `json:"showclienterror"`
	ShowDLNotice        uint8     `json:"showdlnotice"`
	Tooltip             string    `json:"tooltip"`
	ShowNFO             string    `json:"shownfo"`
	TimeType            string    `json:"timetype"`
	AppendSticky        string    `json:"appendsticky"`
	AppendNew           string    `json:"appendnew"`
	AppendPromotion     string    `json:"appendpromotion"`
	AppendPicked        string    `json:"appendpicked"`
	DLIcon              string    `json:"dlicon"`
	BMIcon              string    `json:"bmicon"`
	ShowSmallDescr      string    `json:"showsmalldescr"`
	ShowComNum          string    `json:"showcomnum"`
	ShowLastCom         string    `json:"showlastcom"`
	ShowLastPost        string    `json:"showlastpost"`
	PMNum               uint8     `json:"pmnum"`
	School              uint16    `json:"school"`
	ShowFB              string    `json:"showfb"`
	Page                string    `json:"page"`
	TwoStepSecret       string    `json:"two_step_secret"`
	SeedPoints          float64   `json:"seed_points"`
	SeedPointsPerHour   float64   `json:"seed_points_per_hour"`
	AttendanceCard      int32     `json:"attendance_card"`
	OfferAllowedCount   int32     `json:"offer_allowed_count"`
	SeedPointsUpdatedAt time.Time `json:"seed_points_updated_at"`
	SeedTimeUpdatedAt   time.Time `json:"seed_time_updated_at"`
}

func (o *User) TableName() string {
	return "users"
}
